### PR TITLE
Feat/update the full selected methods

### LINKED ISSUE #10: update the full  selected methods&parms
https://github.com/dataswap/messagehub/blob/main/src/backgroundTask/interface/config.ts

### PR DESCRIPTION
**Pull request by siriusyim**
close #10

### CODE REVIEW

**Review by waynewyang — COMMENTED** [review]
lack of car and car replica

**Review by waynewyang — CHANGES_REQUESTED** [review]
add comments

**Comment by siriusyim** [comment]
> add comments

done

**Comment by siriusyim** [comment]
> lack of car and car replica

Annotated and explained

**Pull request merged**
